### ISSUE TITLE
Excuse me. Could you help me ?

### ISSUE THREAD

**Issue by z-ulrics** [dzalf/openQCM-GUI-Matlab#2]
The default output frequency of OpenQCM is 6mhz, how can I change it to 10Mhz output? Is it by mathematical formula or other methods? Which code handles this function?Thank you!

**Comment by dzalf** [comment]
The typical frequency from the openQCM chips is 10 MHz. The correction factor handles.ALIAS defined in the initialState.m file is applied in line 58 from drawNewGUI.m file

**Comment by z-ulrics** [comment]
Yes, I know the frequency of QCM is 10MHz, but if you use the Arduino IDE to look at the serial port data, OPENQCM defaults to 6MHz output, how is it changed to 10MHz?How does this attribute adjust?I don't know how this process works.Thank you.

**Comment by z-ulrics** [comment]
I mean what does this parameter have to do with?Is it related to the Baud rate?Or some other parameter?

**Comment by dzalf** [comment]
I never mentioned the baudrate. As I explained, that number is a correction factor due to the way the frequency is measured by the Arduino board. What is the fundamental frequency from the crystals that you are testing the openQCM with?

Have a look at the original code developed in Java by Marco Mauro and you will see that he applies exactly the same correction factor to get the QCM's frequency

**Comment by z-ulrics** [comment]
handles.ALIAS = 8000000; % Default value for 10 MHz
You mean that change the frequency of OPENQCM to 10MHz with this line of code?

**Comment by dzalf** [comment]
Please upload a screenshot from the serial string sent by your openQCM

**Comment by z-ulrics** [comment]
![微信截图_20210805222621](https://user-images.githubusercontent.com/85732311/128367096-74040d76-2943-4b35-8dba-0e1869266f5f.png)

**Comment by z-ulrics** [comment]
It is the default serial data

**Comment by dzalf** [comment]
Are you using 10 MHz crystals?

**Comment by z-ulrics** [comment]
yes. the QCM frequency is 10MHz

**Comment by dzalf** [comment]
I see, now I remember and that is correct. It matches what my openQCM board sends:

![photo_2021-08-05_15-52-45](https://user-images.githubusercontent.com/3759916/128371648-6f6165c6-c65f-4bfa-a30c-1ff1be8fd426.jpg)

You need to apply the correction factor, as follows. Take the average of the buffer (if you are using one), then multiply the ALIAS by two and subtract the average value). This would give you something like:

2*8000000 - 6008235 = 10000000 (approx)

Please read lines 58-66 from _drawNewGUI.m_ where this is applied. The difference is that my code assumed that crystals with other frequencies could be used but I never implemented that functionality as I always used 10 MHz crystals 😉 

This was done in the original Java code from Marco Mauro, if the nominal frequency is 10 MHz you need to do this after splitting and buffering your data, in your case that should be 6008233, 6008235, etc.

Sorry about the overall confusion. I had to dig deep in my brain to remember this fact 🤣

**Comment by z-ulrics** [comment]
Aha,I know.I need to use this Formula

**Comment by dzalf** [comment]
Yes, apply that and you should get the right values

May I ask you if you are using the openQCM for a research project? Can you share some details about your application? I am interested... 🤔

**Comment by z-ulrics** [comment]
sure.but I am just starting.Could you give me a contact?

**Comment by dzalf** [comment]
Drop me an email at:

dmelendrez-at-gmail-dot-com

I will be closing this issue. Please open one if you have further questions

**Comment by z-ulrics** [comment]
Hello, can you tell me whether the measured frequency increases or decreases with the increase of the gas mass measured by the QCM sensor?

发自我的iPhone


------------------ Original ------------------
From: Daniel Melendrez ***@***.***&gt;
Date: Thu,Aug 5,2021 11:16 PM
To: dzalf/openQCM-GUI-Matlab ***@***.***&gt;
Cc: z-ulrics ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [dzalf/openQCM-GUI-Matlab] Excuse me. Could you help me ? (#2)





 
Drop me an email at:
 
dmelendrez-at-gmail-dot-com
 
I will be closing this issue. Please open one if you have further questions
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by z-ulrics** [comment]
Hi, I have a question now, as we know, the resonant frequency decreases as the QCM mass increases and the curve decreases, but we apply 10Mhz = 2*ALAS-6Mhz and the resulting frequency increases with mass, how is this handled here? Where is the code for this part? Thank you

**Comment by dzalf** [comment]
There is no logic to be implemented for that. The QCM will respond according to the phenomena occurring at the sensor's surface.
The interpretation of the resulting waveform is part of the postprocessing and analysis, not from the acquisition software
